# Generated by Django 4.0.1 on 2022-01-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='n_col',
            field=models.IntegerField(default=0),
        ),
    ]
