# Generated by Django 4.0.1 on 2022-01-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awebapp', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
